### ISSUE TITLE
Spurious error (race condition?) when moving downloaded IJ zip

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#120]
Another run fixed that... probably some race condition?

EDIT: oh, actually for some reason `robot-server-plugin-0.9.35.zip` is being downloaded twice 😯 

```
Running against IntelliJ version(s): 
211.6693.14-EAP-SNAPSHOT

> Task :uiTests:test

com.virtuslab.gitmachete.uitest.UITestSuite STANDARD_OUT
    Installing IntelliJ(211.6693.14-EAP-SNAPSHOT)
    Fetching https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/211.6693.14-EAP-SNAPSHOT/ideaIC-211.6693.14-EAP-SNAPSHOT.zip into /tmp/ide-probe/cache/dbe67b6ce3d85c36edeccf2e76a497f3
    Fetching https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/test/robot-server-plugin/0.9.35/robot-server-plugin-0.9.35.zip into /tmp/ide-probe/cache/c1dae5b609f24141ebb86911a8b64b4b
    Fetching https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/test/robot-server-plugin/0.9.35/robot-server-plugin-0.9.35.zip into /tmp/ide-probe/cache/c1dae5b609f24141ebb86911a8b64b4b
    Extracting jar:file:/home/plipski/.gradle/caches/modules-2/files-2.1/org.virtuslab.ideprobe/driver_2.12/0.5.0+11-c291a948-SNAPSHOT/36838d5409a1b5212ea7bc584d08fe2b67ef0485/driver_2.12-0.5.0+11-c291a948-SNAPSHOT.jar!/ideprobe_2.13-0.5.0+11-c291a948-SNAPSHOT.zip from jar into /tmp/ide-probe/cache/64eb1ce3786f78032ec978c32c605dfb

com.virtuslab.gitmachete.uitest.UITestSuite > classMethod FAILED
    java.nio.file.FileAlreadyExistsException: /tmp/ide-probe/cache/c1dae5b609f24141ebb86911a8b64b4b
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:450)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
        at java.base/java.nio.file.Files.move(Files.java:1421)
        at org.virtuslab.ideprobe.ProbeExtensions$PathExtension.moveTo(ProbeExtensions.scala:72)
        at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.cacheUri(ResourceProvider.scala:47)
        at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.get(ResourceProvider.scala:26)
        at org.virtuslab.ideprobe.dependencies.ResourceProvider.get(ResourceProvider.scala:12)
        at org.virtuslab.ideprobe.dependencies.ResourceProvider.get$(ResourceProvider.scala:12)
        at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.get(ResourceProvider.scala:22)
        at org.virtuslab.ideprobe.dependencies.PluginDependencyProvider.resolve(DependencyProvider.scala:51)
        at org.virtuslab.ideprobe.dependencies.PluginDependencyProvider.$anonfun$fetch$8(DependencyProvider.scala:43)
        at scala.util.Try$.apply(Try.scala:213)
        at org.virtuslab.ideprobe.dependencies.PluginDependencyProvider.$anonfun$fetch$7(DependencyProvider.scala:43)
        at scala.util.Failure.orElse(Try.scala:224)
        at org.virtuslab.ideprobe.dependencies.PluginDependencyProvider.$anonfun$fetch$6(DependencyProvider.scala:43)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:89)
        at org.virtuslab.ideprobe.dependencies.PluginDependencyProvider.fetch(DependencyProvider.scala:42)
        at org.virtuslab.ideprobe.dependencies.DependencyProvider.fetch(DependencyProvider.scala:76)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.$anonfun$installPlugins$2(IntelliJFactory.scala:54)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
        at java.base/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
        at java.base/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
        at java.base/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.withParallel(IntelliJFactory.scala:74)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.installPlugins(IntelliJFactory.scala:53)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.create(IntelliJFactory.scala:25)
        at org.virtuslab.ideprobe.IntelliJFixture.installIntelliJ(IntelliJFixture.scala:83)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup(ClassFixtures.scala:29)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup$(ClassFixtures.scala:26)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.com$virtuslab$gitmachete$uitest$RunningIntelliJPerSuite$$super$setup(UITestSuite.scala:45)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.setup(UITestSuite.scala:17)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.setup$(UITestSuite.scala:17)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.setup(UITestSuite.scala:45)
        at com.virtuslab.gitmachete.uitest.UITestSuite.setup(UITestSuite.scala)

1 test completed, 1 failed

> Task :uiTests:test FAILED

FAILURE: Build failed with an exception.
```

**Comment by lukaszwawrzyk** [comment]
Bug was caused by calling `transformFixture(fixtureFromConfig(...)` i.e. applying each transformer twice
