### ISSUE TITLE
Race conditon (?): java.nio.file.DirectoryNotEmptyException: /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#145]
First happened on ide-probe **0.10.2**.
Never happened when I was using **0.9.1** to test against IntelliJ 2021.1.x.

See https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/4141/workflows/e92c8168-bb98-4f2a-a1d9-555cf08b98ae/jobs/4357/steps for details:

```
com.virtuslab.gitmachete.uitest.UITestSuite STANDARD_ERROR
    java.io.IOException: [11] Failure while deleting /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw at dir  /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw/system
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$2(ProbeExtensions.scala:246)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$2$adapted(ProbeExtensions.scala:243)
    	at scala.util.Success.foreach(Try.scala:253)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:243)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:221)
    	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)
    	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
    	at org.virtuslab.ideprobe.ProbeExtensions$PathExtension.delete(ProbeExtensions.scala:142)
    	at org.virtuslab.ideprobe.ide.intellij.DownloadedIntelliJ.cleanup(InstalledIntelliJ.scala:205)
    	at org.virtuslab.ideprobe.IntelliJFixture.$anonfun$cleanupIntelliJ$1(IntelliJFixture.scala:94)
    	at org.virtuslab.ideprobe.IntelliJFixture.withRetries(IntelliJFixture.scala:113)
    	at org.virtuslab.ideprobe.IntelliJFixture.cleanupIntelliJ(IntelliJFixture.scala:94)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.$anonfun$teardown$3(ClassFixtures.scala:45)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.$anonfun$teardown$3$adapted(ClassFixtures.scala:45)
    	at scala.Option.foreach(Option.scala:407)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown(ClassFixtures.scala:45)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown$(ClassFixtures.scala:39)
    	at com.virtuslab.gitmachete.uitest.UITestSuite$.com$virtuslab$gitmachete$uitest$RunningIntelliJPerSuite$$super$teardown(UITestSuite.scala:44)
    	at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.teardown(UITestSuite.scala:28)
    	at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.teardown$(UITestSuite.scala:26)
    	at com.virtuslab.gitmachete.uitest.UITestSuite$.teardown(UITestSuite.scala:44)
    	at com.virtuslab.gitmachete.uitest.UITestSuite.teardown(UITestSuite.scala)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
    	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw/system
    	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:247)
    	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
    	at java.base/java.nio.file.Files.delete(Files.java:1141)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$1(ProbeExtensions.scala:240)
    	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    	at scala.util.Try$.apply(Try.scala:213)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:240)
    	... 59 more
    java.io.IOException: [11] Failure while deleting /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw at dir  /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$2(ProbeExtensions.scala:246)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$2$adapted(ProbeExtensions.scala:243)
    	at scala.util.Success.foreach(Try.scala:253)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:243)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:221)
    	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)
    	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
    	at org.virtuslab.ideprobe.ProbeExtensions$PathExtension.delete(ProbeExtensions.scala:142)
    	at org.virtuslab.ideprobe.ide.intellij.DownloadedIntelliJ.cleanup(InstalledIntelliJ.scala:205)
    	at org.virtuslab.ideprobe.IntelliJFixture.$anonfun$cleanupIntelliJ$1(IntelliJFixture.scala:94)
    	at org.virtuslab.ideprobe.IntelliJFixture.withRetries(IntelliJFixture.scala:113)
    	at org.virtuslab.ideprobe.IntelliJFixture.cleanupIntelliJ(IntelliJFixture.scala:94)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.$anonfun$teardown$3(ClassFixtures.scala:45)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.$anonfun$teardown$3$adapted(ClassFixtures.scala:45)
    	at scala.Option.foreach(Option.scala:407)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown(ClassFixtures.scala:45)
    	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown$(ClassFixtures.scala:39)
    	at com.virtuslab.gitmachete.uitest.UITestSuite$.com$virtuslab$gitmachete$uitest$RunningIntelliJPerSuite$$super$teardown(UITestSuite.scala:44)
    	at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.teardown(UITestSuite.scala:28)
    	at com.virtuslab.gitmachete.uitest.RunningIntelliJPerSuite.teardown$(UITestSuite.scala:26)
    	at com.virtuslab.gitmachete.uitest.UITestSuite$.teardown(UITestSuite.scala:44)
    	at com.virtuslab.gitmachete.uitest.UITestSuite.teardown(UITestSuite.scala)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
    	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/ide-probe/instances/intellij-instance-2021.1.3--D4h5NFL1Sw6RlKle0iUAbw
    	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:247)
    	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
    	at java.base/java.nio.file.Files.delete(Files.java:1141)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.$anonfun$postVisitDirectory$1(ProbeExtensions.scala:240)
    	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    	at scala.util.Try$.apply(Try.scala:213)
    	at org.virtuslab.ideprobe.ProbeExtensions$DeletingVisitor.postVisitDirectory(ProbeExtensions.scala:240)
    	... 59 more
```

**Comment by LukaszKontowski** [comment]
@PawelLipski - does this bug still occur for git-machete-intellij-plugin CI pipelines?

**Comment by PawelLipski** [comment]
Haven't seen for a loooong while. Even back in 2021, I've probably only seen it just once. Lemme close the issue, actually
