### ISSUE TITLE
Confusing error when a directory path is passed as a path to the tested plugin

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#234]
...which isn't completely impossible, this happened to us due to a bug in our Gradle code (see https://github.com/VirtusLab/git-machete-intellij-plugin/pull/989#discussion_r930169813).

The exception is rather confusing:

```
com.virtuslab.gitmachete.uitest.UITestSuite STANDARD_OUT
    Installing IntelliJ(2022.1.1)
    Fetching https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2022.1.1/ideaIC-2022.1.1.zip into /tmp/ide-probe/cache/12f7e391f6cf176039f56b609cb2cb18
    Display mode: Xvfb
    Fetching https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_14_1-linux-x64-b2043.45.tar.gz into /tmp/ide-probe/cache/0ffa55e155b185ee81ceddd9704121db
    Extracting jar:file:/home/plipski/.gradle/caches/modules-2/files-2.1/org.virtuslab.ideprobe/driver_2.13/0.36.1/a9adf3a5038d063bd83f5a67fce685f4efb6502c/driver_2.13-0.36.1.jar!/ideprobe_2.12-0.36.1.zip from jar into /tmp/ide-probe/cache/29bf07b0512b7c0bf866965224d1a877
    Fetching https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/intellij/remoterobot/robot-server-plugin/0.11.15/robot-server-plugin-0.11.15.zip into /tmp/ide-probe/cache/85cd505faee53bded778bb86be87ed21

com.virtuslab.gitmachete.uitest.UITestSuite > classMethod FAILED
    java.nio.file.ProviderNotFoundException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider.withParallel(IntelliJProvider.scala:61)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider.installPlugins(IntelliJProvider.scala:43)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider.installPlugins$(IntelliJProvider.scala:31)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.installPlugins(IntelliJProvider.scala:102)
        at org.virtuslab.ideprobe.ide.intellij.IntelliJFactory.setup(IntelliJProvider.scala:129)
        at org.virtuslab.ideprobe.IntelliJFixture.installIntelliJ(IntelliJFixture.scala:92)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup(ClassFixtures.scala:29)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup$(ClassFixtures.scala:26)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.org$virtuslab$ideprobe$junit4$RunningIntelliJPerSuite$$super$setup(UITestSuite.scala:18)
        at org.virtuslab.ideprobe.junit4.RunningIntelliJPerSuite.setup(ClassFixtures.scala:10)
        at org.virtuslab.ideprobe.junit4.RunningIntelliJPerSuite.setup$(ClassFixtures.scala:10)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.setup(UITestSuite.scala:18)
        at com.virtuslab.gitmachete.uitest.UITestSuite.setup(UITestSuite.scala)

        Caused by:
        java.nio.file.ProviderNotFoundException: Provider not found
            at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
            at org.virtuslab.ideprobe.dependencies.Resource$IntellijResource.rootEntries(Resource.scala:63)
            at org.virtuslab.ideprobe.dependencies.Resource$IntellijResource.rootEntries$(Resource.scala:62)
            at org.virtuslab.ideprobe.dependencies.Resource$Plain.rootEntries(Resource.scala:75)
            at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider$PluginArchive$1.<init>(IntelliJProvider.scala:39)
            at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider$PluginArchive$2$.apply(IntelliJProvider.scala:38)
            at org.virtuslab.ideprobe.ide.intellij.IntelliJProvider.$anonfun$installPlugins$2(IntelliJProvider.scala:46)
            at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
            at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
            at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
            at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
            at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
            at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
            at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
            at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
            at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
            at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
            at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
            at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
            at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Would be better if there was e.g. some check in ide-probe code to throw a more helpful error (which would include the provided plugin path as well).

**Comment by PawelLipski** [comment]
In the current `develop` of git-machete-intellij-plugin:
1. run `./gradlew uiTest` as a control to make sure it passes (or at least it doesn't already crash on `classMethod` before any test method runs ;p)
2. change line 303 of build.gradle.kts so that `ui-test.plugin.path` property points to any directory (not to a file): can be just `buildPlugin.outputs.files.first().parent` instead of `.path`
3. run `./gradlew uiTest` again, the error should manifest now
