### ISSUE TITLE
NPE in IntelliJFixture#closeIntellij in case of an unresolved IDE

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#91]
See https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3866/workflows/8bfa0618-2354-4d7e-95bd-316a7c859ff4/jobs/4057 for details, but generally:

First, the IDE hasn't been resolved:

```
java.io.FileNotFoundException: https://d2s4y8xcwt8bet.cloudfront.net/com/jetbrains/intellij/idea/ideaIC/211.4961.30-EAP-CANDIDATE-SNAPSHOT/ideaIC-211.4961.30-EAP-CANDIDATE-SNAPSHOT.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1140)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider.$anonfun$get$1(ResourceProvider.scala:12)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.cacheUri(ResourceProvider.scala:46)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.get(ResourceProvider.scala:26)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider.get(ResourceProvider.scala:12)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider.get$(ResourceProvider.scala:12)
	at org.virtuslab.ideprobe.dependencies.ResourceProvider$Cached.get(ResourceProvider.scala:22)
	at org.virtuslab.ideprobe.dependencies.IntelliJDependencyProvider.resolve(DependencyProvider.scala:28)
	at org.virtuslab.ideprobe.dependencies.IntelliJDependencyProvider.$anonfun$fetch$4(DependencyProvider.scala:17)
	at scala.util.Try$.apply(Try.scala:213)
.............
```

aaaand then `closeIntelliJ` fails:

```
java.lang.NullPointerException
	at org.virtuslab.ideprobe.IntelliJFixture.closeIntellij(IntelliJFixture.scala:103)
	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown(ClassFixtures.scala:37)
	at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.teardown$(ClassFixtures.scala:32)
	at com.virtuslab.gitmachete.uitest.UITestSuite$.org$virtuslab$ideprobe$junit4$RunningIntelliJPerSuite$$super$teardown(UITestSuite.scala:18)
	at org.virtuslab.ideprobe.junit4.RunningIntelliJPerSuite.teardown(ClassFixtures.scala:11)
	at org.virtuslab.ideprobe.junit4.RunningIntelliJPerSuite.teardown$(ClassFixtures.scala:11)
	at com.virtuslab.gitmachete.uitest.UITestSuite$.teardown(UITestSuite.scala:18)
	at com.virtuslab.gitmachete.uitest.UITestSuite.teardown(UITestSuite.scala)
..................
```

**Comment by lukaszwawrzyk** [comment]
Fixed in 0.5.0
